name: General build matrix

on:
  workflow_call:
  push:
    branches: [0.H-branch]
  pull_request:
    branches: [0.H-branch]
    types: [opened, reopened, synchronize, ready_for_review]

# We only care about the latest revision of a PR, so cancel all previous instances.
# Allow running master builds to complete to help with ccache refreshes.
concurrency:
  group: general-build-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# Overall strategy for what sorts of builds to include:
# We want a build for the newest and oldest supported version of each compiler.
# We want a build for each platform.
# We also want to ensure that each of the following tweaks are covered in at
# least one PR build:
# - TILES=1
# - SOUND=1
# - RELEASE=1
# - CMAKE=1
# - LOCALIZE=0
# - LTO=1
# - LIBBACKTRACE=1 (on Linux and Windows)
# - Tests with important mods enabled (Magiclysm)
# - A clang-tidy run
# - SANITIZE=address,undefined
# We try to minimize the number of builds subject to those constraints.
#
# To see what toolchains are available, the following may be useful:
# https://launchpad.net/%7Eubuntu-toolchain-r/+archive/ubuntu/test/+index
# https://apt.llvm.org/

jobs:
  skip-duplicates-code:
    continue-on-error: true
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip_code: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["android/**", "build-data/osx/**", "doc/**", "doxygen_doc/**", "lgtm/**", "msvc-**", "object_creator/**", "tools/**", "utilities/**", "data/**", "lang/**"]'
  skip-duplicates-data:
    continue-on-error: true
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip_data: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["android/**", "build-data/osx/**", "doc/**", "doxygen_doc/**", "lgtm/**", "msvc-**", "object_creator/**", "tools/**", "utilities/**"]'
  matrix-variables:
    permissions:
      contents: none
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      fail_fast: ${{ steps.matrix_vars.outputs.fail_fast }}
      skip_tests: ${{ steps.matrix_vars.outputs.skip_tests }}
      max_parallel: ${{ steps.matrix_vars.outputs.max_parallel }}
    steps:
      - id: matrix_vars
        run: |
          echo "fail_fast=$([ "$GITHUB_REF_NAME" = "0.H-branch" ] && echo false || echo true)" >> $GITHUB_OUTPUT
          echo "skip_tests=$([ "$GITHUB_REF_NAME" = "0.H-branch" ] && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "max_parallel=$( [ "$GITHUB_REF_NAME" = "0.H-branch" ] && echo 20 || echo 1)" >> $GITHUB_OUTPUT
  
  emscripten:
    uses: ./.github/workflows/emscripten.yml
    secrets: inherit
